default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  socket: 5432
  username: vrr
  password: vrr

development:
  <<: *default
  database: verify_ruby_rails_dev

test:
  <<: *default
  database: verify_ruby_rails_test

production:
  <<: *default
  database: verify_ruby_rails
